repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: ['--ignore=E501,W292','--max-line-length=120']
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        args: ['--line-length=120','--skip-string-normalization']
